"""add correct_answer_text and question_type to questions

Revision ID: 0b8121475843
Revises: 8e28b934053f
Create Date: 2025-07-16 17:20:09.994865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8121475843'
down_revision = '8e28b934053f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer_text', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('question_type')
        batch_op.drop_column('correct_answer_text')

    # ### end Alembic commands ###
