"""replace quiz with test and question tables

Revision ID: 18601335b1e9
Revises: 000c0b20aabb
Create Date: 2025-06-10 16:45:31.919986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18601335b1e9'
down_revision = '000c0b20aabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=1700), nullable=False),
    sa.Column('option_a', sa.String(length=1200), nullable=False),
    sa.Column('option_b', sa.String(length=1200), nullable=False),
    sa.Column('option_c', sa.String(length=1200), nullable=False),
    sa.Column('option_d', sa.String(length=1200), nullable=False),
    sa.Column('option_e', sa.String(length=1200), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.String(length=5500), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_table('quizzes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('options', sa.TEXT(), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questions')
    op.drop_table('tests')
    # ### end Alembic commands ###
