"""Make MCQ fields nullable for translation questions

Revision ID: fb5bf482598a
Revises: 0b8121475843
Create Date: 2025-07-16 18:37:38.684705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5bf482598a'
down_revision = '0b8121475843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=1200),
               nullable=True)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=1200),
               nullable=True)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=1200),
               nullable=True)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=1200),
               nullable=True)
        batch_op.alter_column('option_e',
               existing_type=sa.VARCHAR(length=1200),
               nullable=True)
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('option_e',
               existing_type=sa.VARCHAR(length=1200),
               nullable=False)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=1200),
               nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=1200),
               nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=1200),
               nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=1200),
               nullable=False)

    # ### end Alembic commands ###
